#!/usr/bin/env bash
set -u

if [[ "${BUILDKITE_LABEL}" == ":docker: Build and Deploy" ]]; then
  if [[ ${BUILDKITE_BRANCH} == "master" ]] && [[ ${BUILDKITE_PULL_REQUEST} == "false" ]]; then
    echo "--- :docker: Removing tags for deleted branches"
    anontoken=$(curl -fsL --retry 3 'https://auth.docker.io/token?service=registry.docker.io&scope=repository:authelia/oidc-tester-app:pull' | jq -r .token)
    authtoken=$(curl -fs --retry 3 -H "Content-Type: application/json" -X POST -d '{"username": "'${DOCKER_TOKEN_USERNAME}'", "password": "'${DOCKER_TOKEN}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
    dockerbranchtags=$(curl -fsL --retry 3 -H "Authorization: Bearer ${anontoken}" https://registry-1.docker.io/v2/authelia/oidc-tester-app/tags/list | jq -r '.tags[] | select(startswith("PR") | not)' | sed -r '/^(latest|master-[0-9a-f]+|[0-9a-f]{40}|BK([[:digit:]]+)|([[:digit:]]+)\.?([[:digit:]]+)?\.?([[:digit:]]+)?)$/d' | sort)
    githubbranches=$(curl -fs --retry 3 https://api.github.com/repos/authelia/oidc-tester-app/branches | jq -r '.[].name' | sort)
    if [[ -z "${authtoken}" ]]; then
      echo ":warning: docker.io auth token not acquired; DockerHub tag deletions will fail." >&2
    fi
    for BRANCH_TAG in $(comm -23 <(echo "${dockerbranchtags}") <(echo "${githubbranches}")); do
      echo "Removing tag ${BRANCH_TAG} from docker.io"
      curl -fsL --retry 3 -o /dev/null -X "DELETE" -H "Authorization: JWT ${authtoken}" https://hub.docker.com/v2/repositories/authelia/oidc-tester-app/tags/${BRANCH_TAG}/
      for i in {1..5}; do
        for GHCR_VERSION in $(curl -fsL --retry 3 -H "Authorization: Bearer ${GHCR_PASSWORD}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/authelia/packages/container/oidc-tester-app/versions?page=${i}&per_page=100" | jq -j --arg tag ${BRANCH_TAG} '.[] | select(.metadata.container.tags[] | contains($tag)) | .metadata.container.tags[], ",", .id, "\n"'); do
          IFS=',' read -a TAGID <<< ${GHCR_VERSION}
          echo "Removing tag ${TAGID[0]} with id ${TAGID[1]} from ghcr.io"
          curl -fsL --retry 3 -o /dev/null -X "DELETE" -H "Authorization: Bearer ${GHCR_PASSWORD}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/authelia/packages/container/oidc-tester-app/versions/${TAGID[1]}
        done
      done
    done

    echo "--- :docker: Removing tags for merged or closed pull requests"
    dockerprtags=$(curl -fsL --retry 3 -H "Authorization: Bearer ${anontoken}" https://registry-1.docker.io/v2/authelia/oidc-tester-app/tags/list | jq -r '.tags[] | select(startswith("PR"))' | sort)
    githubprs=$(curl -fs --retry 3 https://api.github.com/repos/authelia/oidc-tester-app/pulls | jq -r '.[].number' | sed -e 's/^/PR/' | sort)
    for PR_TAG in $(comm -23 <(echo "${dockerprtags}") <(echo "${githubprs}")); do
      echo "Removing tag ${PR_TAG} from docker.io"
      curl -fsL --retry 3 -o /dev/null -X "DELETE" -H "Authorization: JWT ${authtoken}" https://hub.docker.com/v2/repositories/authelia/oidc-tester-app/tags/${PR_TAG}/
      for i in {1..5}; do
        for GHCR_VERSION in $(curl -fsL --retry 3 -H "Authorization: Bearer ${GHCR_PASSWORD}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/orgs/authelia/packages/container/oidc-tester-app/versions?page=${i}&per_page=100" | jq -j --arg tag ${PR_TAG} '.[] | select(.metadata.container.tags[] | contains($tag)) | .metadata.container.tags[], ",", .id, "\n"'); do
          IFS=',' read -a TAGID <<< ${GHCR_VERSION}
          echo "Removing tag ${TAGID[0]} with id ${TAGID[1]} from ghcr.io"
          curl -fsL --retry 3 -o /dev/null -X "DELETE" -H "Authorization: Bearer ${GHCR_PASSWORD}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/authelia/packages/container/oidc-tester-app/versions/${TAGID[1]}
        done
      done
    done
  fi

  docker logout docker.io
  docker logout ghcr.io
fi
