name: 'Dependabot'
on:
  pull_request: {}
permissions:
  contents: 'write'
  pull-requests: 'write'
jobs:
  automerge:
    name: 'Auto-Merge'
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'authelia/oidc-tester-app'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: 'audit'
      - name: 'Dependabot Fetch Metadata'
        id: 'metadata'
        uses: dependabot/fetch-metadata@21025c705c08248db411dc16f3619e6b5f9ea21a
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Enable Auto-Merge'
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
