name: 'Dependabot'
on:
  pull_request: {}
permissions:
  contents: 'write'
  pull-requests: 'write'
jobs:
  automerge:
    name: 'Auto-Merge'
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'authelia/oidc-tester-app'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: 'audit'
      - name: 'Dependabot Fetch Metadata'
        id: 'metadata'
        uses: dependabot/fetch-metadata@ffa630c65fa7e0ecfa0625b5ceda64399aea1b36
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Enable Auto-Merge'
        run: |
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
